---
- :data:
    :name: Audio
    :type: object
    :schema_type: CreativeWork
    :content_type: entity
    :boost: 10.0
    :features:
      :creatable:
        :allowed: true
      :translatable:
        :allowed: true
      :download:
        :allowed: true
      :serialize:
        :allowed: true
        :serializers:
          :asset: true
          :json: true
          :xml: true
          :indesign: true
    :api:
      :type:
        - CreativeWork
        - MediaObject
        - AudioObject
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :asset:
        :label: Datei
        :type: asset
        :asset_type: audio
        :api:
          :disabled: true
        :ui:
          :edit:
            :readonly: true
      :description:
        :label: Beschreibung
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
        :advanced_search: true
      :content_url:
        :label: Audio URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: content_url
          :parameters:
            :0: asset
        :ui:
          :show:
            :disabled: true
        :api:
          :minimal: true
      :url:
        :label: Inhalt URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
        :api:
          :name: sameAs
        :xml:
          :name: sameAs
      # schema.org: TEXT with KB/MB
      # data-cycle: Integer (Byte)
      :content_size:
        :label: Dateigröße
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Asset
          :method: file_size
          :parameters:
            :0: asset
        :advanced_search: true
      :file_format:
        :label: Dateiformat
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: file_format
          :parameters:
            :0: asset
      :file_type:
        :label: Dateiformat - Klassifizierung
        :type: classification
        :tree_label: Dateiformate
        :default_value:
          :module: DataCycleCore::Utility::DefaultValue::Asset
          :method: file_type_classification
          :parameters:
            :0: asset
        :ui:
          :edit:
            :disabled: true
          :show:
            :content_area: header
      :duration:
        :label: Dauer
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Audio
          :method: duration
          :parameters:
            :0: asset
        :ui:
          :show:
            :options:
              :data-unit: sec
        :api:
          :partial: duration
          :format:
            :append: S
            :prepend: PT
        :advanced_search: true
      :upload_date:
        :label: Hochgeladen am
        :type: date
        :storage_location: value
        :ui:
          :edit:
            :options:
              :placeholder: tt.mm.jjjj
              :class: daterange
        :default_value:
          module: DataCycleCore::Utility::DefaultValue::Date
          method: beginning_of_day
        :advanced_search: true
      :author:
        :label: Fotograf
        :type: linked
        :stored_filter:
          - :with_classification_aliases_and_treename:
              :treeLabel: Inhaltstypen
              :aliases:
                - Person
                - Organisation
      :copyright_holder:
        :label: Rechteinhaber
        :type: linked
        :stored_filter:
          - :with_classification_aliases_and_treename:
              :treeLabel: Inhaltstypen
              :aliases:
                - Person
                - Organisation
      :copyright_year:
        :label: Copyright - Jahr
        :type: number
        :storage_location: value
        :advanced_search: true
      :content_location:
        :label: Ort
        :type: linked
        :stored_filter:
          - :with_classification_aliases_and_treename:
              :treeLabel: Inhaltstypen
              :aliases:
                - Ort
        :validations:
          :max: 1
      :keywords:
        :label: Keywords
        :storage_location: translated_value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Classification
          :method: keywords
          :parameters:
            :0: tags
        :ui:
          :show:
            :disabled: true
      :additional_media_properties:
        :type: mixin
        :name: additional_media_properties
      :additional_audio_properties:
        :type: mixin
        :name: additional_audio_properties
      :tags:
        :type: mixin
        :name: tags
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: 'Audio'
      :meta_data:
        :type: mixin
        :name: meta_data
      :cc_rel:
        :type: mixin
        :name: cc_rel
      :additional_properties:
        :type: mixin
        :name: additional_properties
