---
- :data:
    :name: outdoor_active_external_system
    :type: mixin
    :properties:
      :outdoor_active_system_categories:
        :label: OutdoorActive - System - Kategorien
        :type: classification
        :tree_label: OutdoorActive - System - Kategorien
        :global: true
        :ui:
          :show:
            :content_area: header
      :outdoor_active_system_source_keys:
        :label: OutdoorActive - System - Quellen
        :type: classification
        :tree_label: OutdoorActive - System - Quellen
        :global: true
        :validations:
          :max: 1
        :ui:
          :show:
            :content_area: header
