speedups:
  each_with_index_vs_while: false

exclude_paths:
  - 'app/controllers/data_cycle_core/api/v1/api_base_controller.rb'
  - 'app/models/data_cycle_core/callbacks.rb'
  - 'app/uploaders/data_cycle_core/pdf_uploader.rb'
  - 'config/deploy/review.rb'
  - 'test/dummy/config/environments/review.rb'
  - 'test/dummy/config/environments/development.rb'
  - 'test/dummy/config/environments/production.rb'
  - 'test/dummy/config/environments/staging.rb'
  - 'node_modules/**/*'
  - 'tmp/**/*'
  - 'cache/**/*'
  - 'vendor/**/*'
  - 'app/models/data_cycle_core/generic/bergfex/import_snow_resorts.rb'
  - 'app/models/data_cycle_core/generic/bergfex/import_ski_resorts_new.rb'
