:center: 
  - 13.34576
  - 47.69642
:zoom: 7
:editor: 'MapLibreGl'
:styles:
  - :id: osm
    :value: 'OSM'
  # - :id: basemap
  #   :value: 'BaseMapAt'
:type_colors:
  default: '#1D6996' # dark blue
  hover: '#EDAD08' # yellow
  'dcls:Tour': '#73AF48' # light green
  'dcls:POI': '#1D6996' # dark blue
  'dcls:Örtlichkeit': '#0F8554' # dark green
  'dcls:Gastronomischer Betrieb': '#666666' # gray
  'dcls:Unterkunft': '#CC503E' # red
  