:active_storage: 
  :enabled: false
  :asset_types:
    - DataCycleCore::Audio
    - DataCycleCore::DataCycleFile
    - DataCycleCore::Pdf
    - DataCycleCore::SrtFile
    - DataCycleCore::TextFile
    - DataCycleCore::Video
