- "0 0 * * 1":
    - data_cycle_core:notifications:send[week]

- "0 0 * * *":
    - data_cycle_core:notifications:send[day]
    - dc:privacy:lock_users_without_consent
    - data_cycle_core:clear:activities

- "0 2 * * *":
    - data_cycle_core:db:dump[backup_production]

- "0 3 * * *":
    - data_cycle_core:mongo:dump_backup
