---
- :data:
    :name: Organization
    :type: object
    :schema_type: Organization
    :content_type: entity
    :boost: 1.0
    :features:
      :translatable:
        :allowed: true
      :creatable:
        :allowed: true
      :download:
        :allowed: true
      :serialize:
        :allowed: true
        :serializers:
          :xml: true
          :json: true
          :indesign: true
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :postal_address:
        :type: mixin
        :name: postal_address
      :contact_info:
        :type: mixin
        :name: contact_info
      :description:
        :label: Text
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: full
        :advanced_search: true
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
      :member:
        :label: Mitglieder
        :type: linked
        :stored_filter:
          -
            :with_classification_aliases_and_treename:
              :treeLabel: Inhaltstypen
              :aliases:
                - Person
                - Organisation
        :inverse_of: member_of
        :link_direction: inverse
      :content_location:
        :label: Standort
        :type: linked
        :stored_filter:
          -
            :with_classification_aliases_and_treename:
              :treeLabel: Inhaltstypen
              :aliases:
                - Ort
        :api:
          :name: location
      :linked_data:
        :type: mixin
        :name: linked_data
      :subject_of:
        :label: Thema von
        :type: linked
        :inverse_of: about
        :link_direction: inverse
        :global: true
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Organisation"
      :cc_rel:
        :type: mixin
        :name: cc_rel
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
