- HRS - Image-Categories | all:
  - $$other
  - $$info
  - $$outdoor
  - $$exterior
  - $$outdoor_facility
  - $$surroundings
  - $$view
  - $$interior
  - $$lobby
  - $$wellness
  - $$restaurant
  - $$room
  - $$bathroom
