---
- :data:
    :name: title
    :type: mixin
    :properties:
      :name:
        :label: Firmenname
        :type: string
        :storage_location: column
        :search: true
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: none
        :normalize:
          :id: company
          :type: company
      :legal_name:
        :label: Legal Name
        :storage_location: translated_value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::String
          :method: concat
          :parameters:
            :0:
              :type: content
              :name: name
        :ui:
          :show:
            :disabled: true
        :api:
          :minimal: true
