---
- :data:
    :name: See
    :type: object
    :schema_type: Place
    :content_type: entity
    :boost: 100.0
    :features:
      :overlay:
        :allowed: true
      :translatable:
        :allowed: true
      :download:
        :allowed: true
      :serialize:
        :allowed: true
        :serializers:
          :xml: true
          :json: true
          :indesign: true
    :api:
      :type: 
        - Place
        - Landform
        - BodyOfWater
    :properties:
      :id:
        :label: id
        :type: key
      :overlay:
        :label: Overlay
        :type: embedded
        :template_name: BodyOfWaterOverlay
        :translated: true
        :validations:
          :max: 1
      :title:
        :type: mixin
        :name: title
      :tourism_region:
        :label: Tourismus-Region
        :type: classification
        :tree_label: Tourismus-Regionen
        :global: true
        :ui:
          :show:
            :content_area: header
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :water_temp:
        :label: Seetemperatur
        :type: object
        :storage_location: value
        :advanced_search: true
        :properties:
          :temperature:
            :label: Temperatur
            :type: number
            :storage_location: value
            :validations:
              :format: float
            :ui:
              :edit:
                :options:
                  :data-unit: °C
              :show:
                :options:
                  :data-unit: °C
            :advanced_search: true
          :temp_at:
            :label: vom
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :class: daterange
                  :placeholder: 'tt.mm.jjjj --:--'
            :advanced_search: true
          :quality:
            :label: Wasserqualität
            :type: string
            :storage_location: value
        :api:
          :v4:
            :partial: property_value
            :type: PropertyValue
            :transformation:
              :method: combine
              :name: additionalProperty
      :area:
        :label: Fläche
        :type: number
        :storage_location: value
        :validations:
          :format: float
        :ui:
          :edit:
            :options:
              :data-unit: km²
          :show:
            :options:
              :data-unit: km²
        :advanced_search: true
        :api:
          :v4:
            :partial: property_value
            :type: PropertyValue
            :transformation:
              :method: combine
              :name: additionalProperty
      :depth:
        :label: Tiefe
        :type: number
        :storage_location: value
        :validations:
          :format: float
        :ui:
          :edit:
            :options:
              :data-unit: m
          :show:
            :options:
              :data-unit: m
        :advanced_search: true
        :api:
          :v4:
            :partial: property_value
            :type: PropertyValue
            :transformation:
              :method: combine
              :name: additionalProperty
      :geo:
        :type: mixin
        :name: geo
      :opening_hours_specification:
        :type: mixin
        :name: opening_hours_specification
      :url:
        :label: Link
        :type: string
        :storage_location: translated_value
        :api:
          :v4:
            :name: sameAs
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: 'Badeseen'
      :meta_data:
        :type: mixin
        :name: meta_data
      :cc_rel:
        :type: mixin
        :name: cc_rel
      :additional_properties:
        :type: mixin
        :name: additional_properties
