---
- :data:
    :name: BodyOfWaterOverlay
    :type: object
    :schema_type: Place
    :content_type: embedded
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Name
        :type: string
        :storage_location: column
        :search: true
      :url:
        :label: Link
        :type: string
        :storage_location: translated_value
        :api:
          :name: sameAs
        :xml:
          :name: sameAs
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
