---
- :data:
    :name: meta_data
    :type: mixin
    :properties:
      :universal_classifications:
        :label: Classifications
        :type: classification
        :external: true
        :universal: true
        :ui:
          :show:
            :content_area: header
            :partial: universal_classifications
      :date_created:
        :label: Erstellungsdatum
        :type: datetime
        :storage_location: value
        :ui:
         :edit:
           disabled: true
         :show:
           :type: date
      :date_modified:
        :label: Änderungsdatum
        :type: datetime
        :storage_location: value
        :ui:
         :edit:
           disabled: true
         :show:
           :type: date
      :date_deleted:
        :label: Gelöschtdatum
        :type: datetime
        :storage_location: value
        :ui:
         :edit:
           disabled: true
         :show:
           :type: date
      :slug:
        :label: slug
        :storage_location: column
        :type: slug
        :default_value:
          module: DataCycleCore::Utility::DefaultValue::Slug
          method: generate_slug
        :advanced_search: true
        :search: true
        :ui:
          :bulk_edit:
            :disabled: true
        :api:
          :name: dc:slug
      :external_key:
        :label: external_key
        :type: string
        :storage_location: column
        :ui:
          :show:
            :disabled: true
          :edit:
            :disabled: true
        :api:
          :disabled: true
