---
- :data:
    :name: tags
    :type: mixin
    :properties:
      :keywords_medienarchive:
        :label: MediaArchive - Tags
        :type: classification
        :tree_label: MediaArchive - Tags
        :external: true
        :ui:
          :show:
            :content_area: header
      :keywords_eyebase:
        :label: Eyebase - Tags
        :type: classification
        :tree_label: Eyebase - Tags
        :external: true
        :ui:
          :show:
            :content_area: header
      :status_eyebase:
        :label: Eyebase - Status
        :type: classification
        :tree_label: Eyebase - Status
        :external: true
        :ui:
          :show:
            :content_area: header
      :keywords_celum:
        :label: Celum - Keywords
        :type: classification
        :tree_label: Celum - Keywords
        :external: true
        :ui:
          :show:
            :content_area: header
      :folders_celum:
        :label: Celum - Folders
        :type: classification
        :tree_label: Celum - Folders
        :external: true
        :ui:
          :show:
            :content_area: header
      :asset_collections_celum:
        :label: Celum - Asset Collection
        :type: classification
        :tree_label: Celum - Asset Collections
        :external: true
        :ui:
          :show:
            :content_area: header
      :types_of_use_celum:
        :label: Celum - Verwendungsart
        :type: classification
        :tree_label: Celum - Verwendungsart
        :external: true
        :ui:
          :show:
            :content_area: header
      :hrs_image_categories:
        :label: HRS - Image-Categories
        :type: classification
        :tree_label: HRS - Image-Categories
        :external: true
        :ui:
          :show:
            :content_area: header
