---
- :data:
    :name: content_classifications
    :type: mixin
    :properties:
      :tags:
        :label: Tags
        :type: classification
        :tree_label: Tags
        :global: true
        :ui:
          :show:
            :content_area: header
      :feratel_identity_keywords:
        :label: Feratel Identity Server Keywords
        :type: classification
        :tree_label: Feratel Identity Server Keywords
        :ui:
          :show:
            :content_area: header
      :feratel_identity_claims:
        :label: Feratel Identity Server Claims
        :type: classification
        :tree_label: Feratel Identity Server Claims
        :ui:
          :show:
            :content_area: header
      :feratel_identity_realms:
        :label: Feratel Identity Server Realms
        :type: classification
        :tree_label: Feratel Identity Server Realms
        :ui:
          :show:
            :content_area: header
      :feratel_identity_db_code:
        :label: Feratel Identity Server dbCode
        :type: classification
        :tree_label: Feratel Identity Server dbCodes
        :ui:
          :show:
            :content_area: header
      :feratel_identity_role:
        :label: Feratel Identity Server Role
        :type: classification
        :tree_label: Feratel Identity Server Roles
        :ui:
          :show:
            :content_area: header
      :feratel_identity_user_type:
        :label: Feratel Identity Server userType
        :type: classification
        :tree_label: Feratel Identity Server userTypes
        :ui:
          :show:
            :content_area: header
      :output_channel:
        :label: Ausgabekanal
        :type: classification
        :tree_label: Ausgabekanäle
        :global: true
        :ui:
          :show:
            :content_area: header
