---
- :data:
    :name: feratel_offer_classifications
    :type: mixin
    :properties:
      :feratel_status:
        :label: Feratel - Status
        :type: classification
        :tree_label: Feratel - Status
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :feratel_accommodation_type:
        :label: Feratel - Unterkunftstypen
        :type: classification
        :tree_label: Feratel - Unterkunftstypen
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :feratel_product_type:
        :label: Feratel - Produktarten
        :type: classification
        :tree_label: Feratel - Produktarten
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :holiday_themes:
        :label: Feratel - Urlaubsthemen
        :type: classification
        :tree_label: Feratel - Urlaubsthemen
        :external: true
        :ui:
          :show:
            :content_area: header
      :feratel_offer_status:
        :label: Feratel - Angebot - Status
        :type: classification
        :tree_label: Feratel - Angebot - Status
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :feratel_price_type:
        :label: Feratel - Preis - Typ
        :type: classification
        :tree_label: Feratel - Preis - Typ
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :feratel_locations:
        :label: Feratel - Ort
        :type: classification
        :tree_label: Feratel - Orte
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
