---
- :data:
    :name: Route
    :type: object
    :schema_type: Place
    :content_type: entity
    :boost: 100.0
    :features:
      :translatable:
        :allowed: true
      :download:
        :allowed: true
      :overlay:
        :allowed: true
      :serialize:
        :allowed: true
        :serializers:
          :xml: true
          :json: true
          :gpx: true
          :indesign: true
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_location: column
        :search: true
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: none
        :api:
          :minimal: true
      :internal_name:
        :label: Interner Name
        :type: string
        :storage_location: column
        :search: true
        :api:
          :disabled: true
      :owner:
        :label: Besitzer
        :type: classification
        :tree_label: Besitzer
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: header
      :referencetype:
        :label: Typ des Verortungsobjektes
        :type: classification
        :tree_label: Typ des Verortungsobjektes
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: header
      :orgcode:
        :label: Organisationscode
        :type: classification
        :tree_label: Organisationscode
        :ui:
          :show:
            :content_area: header
      :minortyperef:
        :label: Ergänzungstyp
        :type: classification
        :tree_label: Ergänzungstyp
        :ui:
          :show:
            :content_area: header
      :sustainer:
        :label: Erhalter
        :type: classification
        :tree_label: Erhalter
        :ui:
          :show:
            :content_area: header
      :atroute:
        :label: Österreichische Radrouten
        :type: classification
        :tree_label: Österreichische Radrouten
        :ui:
          :show:
            :content_area: header
      :eurovelo:
        :label: EURO Velo Radrouten
        :type: classification
        :tree_label: EURO Velo Radrouten
        :ui:
          :show:
            :content_area: header
      :bikecomfort:
        :label: Schwierigkeitsgrad
        :type: classification
        :tree_label: Schwierigkeitsgrad
        :ui:
          :show:
            :content_area: header
      :bikeroutestate:
        :label: Radroutenstatus
        :type: classification
        :tree_label: Radroutenstatus
        :ui:
          :show:
            :content_area: header
      :signage:
        :label: Beschilderung
        :type: classification
        :tree_label: Beschilderung
        :ui:
          :show:
            :content_area: header
      :bikeroute:
        :label: Radroutentyp
        :type: classification
        :tree_label: Radroutentyp
        :ui:
          :show:
            :content_area: header
      :routes:
        :label: Gesamtroute
        :type: linked
        :template_name: Gesamtroute
        :inverse_of: sections
        :api:
          minimal: true
      :route_name:
        :label: Name der Gesamtroute
        :type: computed
        :storage_location: value
        :compute:
          :type: string
          :module: Utility::Compute::String
          :method: linked_gip_route_attribute
          :linked_attribute: name
          :parameters:
            :linked: routes
      :route_number:
        :label: Nummer der Gesamtroute
        :type: computed
        :storage_location: value
        :compute:
          :type: string
          :module: Utility::Compute::String
          :method: linked_gip_route_attribute
          :linked_attribute: route_number
          :parameters:
            :linked: routes
      :round_trip:
        :label: Rundkurs
        :type: boolean
        :storage_location: value
        :advanced_search: true
        :default_value: 'false'
        :global: true
      :one_way:
        :label: Einbahn
        :type: boolean
        :storage_location: value
        :advanced_search: true
        :default_value: 'false'
        :global: true
      :line:
        :label: Route
        :storage_location: column
        :type: geographic
        :ui:
          :edit:
            :disabled: false
            :type: LineString
            :options:
              :data_upload: true
      :subject_of:
        :label: Thema von
        :type: linked
        :inverse_of: about
        :link_direction: inverse
        :global: true
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: 'Route'
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
