---
- :data:
    :name: ImageVariant
    :type: object
    :schema_type: CreativeWork
    :content_type: embedded
    :features:
      :image_editor:
        :allowed: true
    :api:
      :type:
        - CreativeWork
        - MediaObject
        - ImageObject
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Name
        :type: string
        :storage_location: column
        :search: true
      :asset:
        :label: Datei
        :type: asset
        :asset_type: image
        :api:
          :disabled: true
      :content_url:
        :label: Bild URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: content_url
          :parameters:
            :0: asset
        :ui:
          :show:
            :disabled: true
        :api:
          :minimal: true
      :thumbnail_url:
        :label: Thumbnail URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Image
          :method: thumbnail_url
          :parameters:
            :0: asset
        :ui:
          :show:
            :partial: preview_image
        :api:
          :minimal: true
      :url:
        :label: Inhalt URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
        :api:
          :name: sameAs
        :xml:
          :name: sameAs
        :ui:
          :edit:
            :disabled: true
      :width:
        :label: Breite
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Image
          :method: width
          :parameters:
            :0: asset
        :ui:
          :show:
            :options:
              :data-unit: px
        :api:
          :partial: property_value
          :type: QuantitativeValue
          :unit_text: pixel
          :unit_code: E37
          :transformation:
            :method: nest
            :name: width
        :advanced_search: true
      :height:
        :label: Höhe
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Image
          :method: height
          :parameters:
            :0: asset
        :ui:
          :show:
            :options:
              :data-unit: px
        :api:
          :partial: property_value
          :type: QuantitativeValue
          :unit_text: pixel
          :unit_code: E37
          :transformation:
            :method: nest
            :name: height
        :advanced_search: true
      # schema.org: TEXT with KB/MB
      # data-cycle: Integer (Byte)
      :content_size:
        :label: Dateigröße
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Asset
          :method: file_size
          :parameters:
            :0: asset
        :advanced_search: true
      :file_format:
        :label: Dateiformat
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: file_format
          :parameters:
            :0: asset
      :upload_date:
        :label: Hochgeladen am
        :type: date
        :storage_location: value
        :ui:
          :edit:
            :options:
              :placeholder: tt.mm.jjjj
              :class: daterange
        :default_value:
          module: DataCycleCore::Utility::DefaultValue::Date
          method: beginning_of_day
        :advanced_search: true
      :gravity:
        :type: mixin
        :name: gravity
      :image_proxy:
        :type: mixin
        :name: image_proxy
      :dummy:
        :label: invisible
        :type: string
        :storage_location: translated_value
        :default_value: do_not_show
        :api:
          :disabled: true
        :xml:
          :disabled: true
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true
      :meta_data:
        :type: mixin
        :name: meta_data
